apiVersion: v2
name: myapp-chart
description: A Helm chart for Mini-Notizblock Full-Stack Application

type: application

version: 0.1.0

appVersion: "1.0.0"

keywords:
  - notizblock
  - frontend
  - backend
  - postgresql

home: https://github.com/yourname/mini-notizblock

maintainers:
  - name: Your Name
    email: your.email@example.com

dependencies:
  - name: postgresql
    version: "15.5.32"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
