{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "myapp-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    version: stable
{{- end }}