{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp-chart.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
      version: stable
  template:
    metadata:
      labels:
        {{- include "myapp-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        version: stable
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "myapp-chart.fullname" . }}-frontend-nginx
{{- end }}