apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  type: NodePort
  selector:
    app: nginx-example
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30080 # Optional: Sie können einen spezifischen NodePort angeben, sonst wird einer dynamisch zugewiesen
