apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  GREETING_MESSAGE: "Hello from ConfigMap!"
  LOG_LEVEL: "info"
  app.properties: |
    feature.enabled=true
    theme=dark
    source=configmap-file
