name: CI Pipeline - Build & Push Docker Images

on:
  push:
    branches: [main, master]
    paths:
      - 'k8s/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'k8s/**'

env:
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mini-notizblock-frontend
  BACKEND_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mini-notizblock-backend

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Frontend Tests
        run: |
          cd ./k8s/frontend
          npm ci
          npm test || echo "No tests found"

      - name: Backend Tests
        run: |
          cd ./k8s/backend
          npm ci
          npm test || echo "No tests found"

  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Tags
        id: tags
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./k8s/frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.BRANCH_NAME }}
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.COMMIT_SHA }}
          build-args: |
            VITE_API_URL=/api

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./k8s/backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ env.BACKEND_IMAGE_NAME }}:${{ env.BRANCH_NAME }}
            ${{ env.BACKEND_IMAGE_NAME }}:${{ env.COMMIT_SHA }}

      - name: Image Status
        run: |
          echo "Images erfolgreich gebaut und gepusht:"
          echo "  - ${{ env.FRONTEND_IMAGE_NAME }}:latest"
          echo "  - ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.BRANCH_NAME }}"
          echo "  - ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.COMMIT_SHA }}"
          echo "  - ${{ env.BACKEND_IMAGE_NAME }}:latest"
          echo "  - ${{ env.BACKEND_IMAGE_NAME }}:${{ env.BRANCH_NAME }}"
          echo "  - ${{ env.BACKEND_IMAGE_NAME }}:${{ env.COMMIT_SHA }}"

  # Helm Chart aktualisieren
  update-helm:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm Chart Values
        run: |
          # Image Tags in values.yaml aktualisieren
          sed -i "s|repository:.*frontend-image|repository: ${{ env.FRONTEND_IMAGE_NAME }}|g" ./k8s/myapp-chart/values.yaml
          sed -i "s|repository:.*backend-image|repository: ${{ env.BACKEND_IMAGE_NAME }}|g" ./k8s/myapp-chart/values.yaml
          sed -i "s|tag:.*|tag: \"${{ env.COMMIT_SHA }}\"|g" ./k8s/myapp-chart/values.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/myapp-chart/values.yaml
          git commit -m "Update image tags to ${{ env.COMMIT_SHA }}" || echo "No changes to commit"
          git push
